print ("_____________")
print ("|   |   |   |")
print ("|___|___|___|")
print ("|   |   |   |")
print ("|___|___|___|")
print ("|   |   |   |")
print ("|___|___|___|")
Eingabe = input("wohin möchtest du gehen? ")
if str(Eingabe) == "1":
    print ("_____________")
    print ("| x |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
if str(Eingabe) == "2":
    print ("_____________")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
if str(Eingabe) == "3":
    print ("_____________")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
if str(Eingabe) == "4":
    print ("_____________")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
if str(Eingabe) == "5":
    print ("_____________")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
if str(Eingabe) == "6":
    print ("_____________")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
if str(Eingabe) == "7":
    print ("_____________")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
if str(Eingabe) == "8":
    print ("_____________")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
if str(Eingabe) == "9":
    print ("_____________")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
    print ("|   |   |   |")
    print ("|___|___|___|")
    
